### PR TITLE
Eliminate unnecessary modify requests when provisioning

### PR DESCRIPTION
**Pull request by cyrilbrugman**
Added a check eliminating unnecessary modify requests when it would provision 0 nodes

### CODE REVIEW

**Comment by marklagendijk** [comment]
This is an important improvement. EC2 doesn't like it when it gets hammered by change requests which request exactly the same as the previous request.
This can slow down node creation and cause other issues.
So, merge, plz!

**Comment by borgstrom** [comment]
@cyrilbrugman #25 has landed in master now -- can you fix up the merge conflicts here?  I'd love to see this land too before the next release.

cc @schmutze  :)

**Comment by cyrilbrugman** [comment]
@borgstrom I have fixed the merge, and added my other changes in a separate branch/pull request.

**Comment by schmutze** [comment]
@borgstrom  released as ec2-fleet-1.1.7

**Pull request merged**
