### PR TITLE
Fix 'burst' of booting nodes

### PR DESCRIPTION
**Pull request by marklagendijk**
Currently the following happens when 'excess workload' occurs:

- The plugin calculates how many nodes should be started, and starts them.
- The nodes are booting.
- The plugin calculates how many nodes should be started, and starts them.
- The nodes + the previous nodes are booting.
- Etc.
- The max number of nodes is reached.

The problem is that the plugin does not consider the 'new nodes' it is booting in the 'excess workload' calculation.

This pull requests fixes that, by maintaining a cache of these 'new nodes' and using them in the 'excess workload calculation'.

### CODE REVIEW

**Comment by marklagendijk** [comment]
This fix has been made by my colleague @cyrilbrugman who also did #26 and #29.
I just reapplied it based on the latest master.

We have been using this fix for several months on our production Jenkins server. It works well :).

**Comment by marklagendijk** [comment]
@jzila can you review this (I saw you also did the other reviews).

**Comment by terma** [comment]
hi @marklagendijk 

I've checked Jenkins logic around provision, looks like Jenkins correctly consider planned nodes for ```excessWorkload``` calculation [code here](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/slaves/NodeProvisioner.java#L668), additionaly that confirmed by [article](https://support.cloudbees.com/hc/en-us/articles/115000060512-New-Shared-Agents-Clouds-are-not-being-provisioned-for-my-jobs-in-the-queue-when-I-have-agents-that-are-suspended)

My theory that we have overprovision because of incorrect adding of new nodes to Jenkins. Here [code](https://github.com/jenkinsci/ec2-fleet-plugin/blob/master/src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java#L449) how we do that now, so we add nodes directly to jenkins while it should be by ```PlannedNode``` [more about that](https://groups.google.com/forum/#!topic/jenkinsci-dev/SYerQ-8E-10)

**Comment by marklagendijk** [comment]
@terma thanks for the feedback!
It totally makes sense that this would already be in Jenkins core! 
It would be really awesome if this would be implemented correctly in the plugin.

**Comment by marklagendijk** [comment]
I closed this pull request and opened issue #76 instead.

**Pull request closed without merging**
