### PR TITLE
fix fsRoot reset

### PR DESCRIPTION
**Pull request by tsDaenor**
this will fix [this issue](https://issues.jenkins-ci.org/browse/JENKINS-43799?jql=project%20%3D%20JENKINS%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20component%20%3D%20%27ec2-fleet-plugin%27)

### CODE REVIEW

**Comment by marklagendijk** [comment]
I am currently having issues because of this issue. Would be happy if it could be merged and released.

**Comment by CoRfr** [comment]
Could someone merge this PR?
I'm also facing this issue :(

**Comment by zvymazal** [comment]
There's still the option of forking this repo, merging in this PR and building the plugin manually. That's at least what I did till it's resolved upstream.

**Comment by CoRfr** [comment]
Of course but what I wanted to avoid is to manage my own build+delivery for
this plug-in while there is an official one.

On Jun 13, 2017 12:48 AM, "zvymazal" <notifications@github.com> wrote:

There's still the option of forking this repo, merging in this PR and
building the plugin manually. That's at least what I did till it's resolved
upstream.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/jenkinsci/ec2-fleet-plugin/pull/6#issuecomment-308035604>,
or mute the thread

**Comment by schmutze** [comment]
Hi Folks, sorry for the delay. Working to accept this PR.

**Comment by schmutze** [comment]
Thank you @tsDaenor . 
Merged and released in 1.1.4.

**Pull request merged**
