### PR TITLE
Many New Features and Bugfixes

### PR DESCRIPTION
**Pull request by jzila**
I recognize that it's not best practice to combine multiple features/bugfixes into one PR, but there were a few heavy refactors that were needed to make this plugin stable, and features were sprinkled throughout that process. Once this is in, it'll be a far better baseline for continuing best practice work.

Also exists as awslabs/ec2-spot-jenkins-plugin#9

## Bugfixes
- [x] [JENKINS-36429](https://issues.jenkins-ci.org/browse/JENKINS-36429) Don't scale to more instances than the maximum limit
- [x] Don't provision jobs on instances that have been terminated
- [x] [JENKINS-38115](https://issues.jenkins-ci.org/browse/JENKINS-38115) Remove an instance once EC2 has successfully terminated it
- [x] Fixed miscellaneous plugin crashes
- [x] [JENKINS-36242](https://issues.jenkins-ci.org/browse/JENKINS-36242) Don't try to terminate already-terminated instances
- [x] [JENKINS-36405](https://issues.jenkins-ci.org/browse/JENKINS-36405) Make instance termination reliable

## Features
- [x] [JENKINS-35426](https://issues.jenkins-ci.org/browse/JENKINS-35426) Assign labels to fleet instances
- [x] [JENKINS-37180](https://issues.jenkins-ci.org/browse/JENKINS-37180) Specify number of executors per fleet instance
- [x] Specify minimum fleet size
- [x] Specify custom filesystem root

### CODE REVIEW

**Comment by thebenwaters** [comment]
+1

**Comment by weargoggles** [comment]
You may have your reasons for not releasing this, but I'll just say I would really like it if you did

**Comment by weargoggles** [comment]
@ndeloof Do you think there's any change of this being accepted?

**Comment by ndeloof** [comment]
I'm not a maintainer here, just proposed some fixes to initial implementation.

**Comment by weargoggles** [comment]
paging @schmutze - any chance of this being accepted as is? if you need changes, what are they?

**Comment by schmutze** [comment]
Think I finally got permissions over the holiday....good times. Will try to accept this asap.

**Comment by schmutze** [comment]
Awesome, thanks so much @jzila !

**Comment by schmutze** [comment]
@jzila:

Can you help me understand if
https://github.com/jenkinsci/ec2-fleet-plugin/pull/1
and / or
https://github.com/jenkinsci/ec2-fleet-plugin/pull/2
are still relevant after accepting this pull?

**Comment by jzila** [comment]
They are not. #3 implemented those fixes as well.

**Comment by thebenwaters** [comment]
Any timeline on release?

**Comment by schmutze** [comment]
@thebenwaters working on it today.

**Comment by schmutze** [comment]
Quick update: I did release the new version, but still investigating why it isn't showing up in the update center. 
https://repo.jenkins-ci.org/releases/com/amazon/jenkins/fleet/ec2-fleet/1.1.2/
Hopefully just something I'm doing wrong. I'll update when I get it showing up.

**Comment by schmutze** [comment]
OK, it appears the update finally made it to the update center. Looking forward to feedback.

**Pull request merged**
