### PR TITLE
JENKINS-37180 Add num executors configuration parameter

### PR DESCRIPTION
**Pull request by matiangul**

### CODE REVIEW

**Comment by chrisburrell** [comment]
+1 Would be great to have this soon :) 👍

**Comment by MartinNuc** [comment]
+1 I was just searching how to do it :)

**Comment by gabriellhrn** [comment]
+1

**Comment by thebenwaters** [comment]
+1

**Comment by schmutze** [comment]
@matiangul - Thanks so much for the input.
This was addressed in https://github.com/jenkinsci/ec2-fleet-plugin/pull/3, so closing this out.
Let me know if I missed anything.

**Comment by matiangul** [comment]
Yeah everything is there. Thx :1st_place_medal:

**Pull request closed without merging**
