### PR TITLE
Add UnweightedScaling option

### PR DESCRIPTION
**Pull request by bardyr**

### CODE REVIEW

**Comment by orrc** [comment]
There's no description or link to a JIRA ticket here, so it's unclear what the motivation is.

The added documentation says this will "Scale as soon as a build is queued", but `provision(Label, int)` is only called by the system when it determines new nodes are required, so the implementation doesn't match the documentation.

The current implementation is correct, and matches the contract of the `provision()` method, i.e. to provision as many executors as required, so it's unclear why this PR wants to change that.

If you want to provision one instance for each build, just set your executors per instance to 1, and you'll have the same effect with the existing code.

**Comment by bardyr** [comment]
@orrc my issue is that `provision()` is called with the number of jobs in queue, the plugin will then perform the following calculation `int weightedExcessWorkload = Math.round((float)excessWorkload / this.numExecutors);` since the number of jobs in queue will usually be much lower then number of current executors the plugin will not provision more executors unless a lot of jobs are in queue.

I'm not sure if this is expected or wanted behaviour so I simple bypassed the weighting.

**Comment by schmutze** [comment]
Can someone let me know if this is still relevant or covered in #25 ?

**Comment by borgstrom** [comment]
This PR:

> since the number of jobs in queue will usually be much lower then number of current executors the plugin will not provision more executors unless a lot of jobs are in queue.

#25:

> We have very low usage over the weekends, which means we experience jobs timing out because a second job never enters the queue to trigger the scale up.

Sounds like the same use-case to me.  I believe this can be closed.

**Comment by schmutze** [comment]
Thanks @borgstrom and @oleg-nenashev 
Closing this PR. Feel free to let me know if I misunderstood anything.

**Pull request closed without merging**
