### PR TITLE
Label based configuration

### PR DESCRIPTION
**Pull request by terma**
This feature auto manages EC2 Spot Fleet or ASG based Fleets for Jenkins based on 
label attached to Jenkins Jobs.

With this feature user of EC2 Fleet Plugin doesn't need to have pre-created AWS resources 
to start configuration and run Jobs. Plugin required just AWS Credentials 
with permissions to be able create resources.

# How It Works

- Plugin detects all labeled Jobs where Label starts from Name configured in plugin configuration ```Cloud Name```
- Plugin parses Label to get Fleet configuration
- Plugin creates dedicated fleet for each unique Label
  - Plugin uses [CloudFormation Stacks](https://aws.amazon.com/cloudformation/) to provision Fleet and all required resources
- When Label is not used by any Job Plugin deletes Stack and release resources

### CODE REVIEW

**Comment by terma** [comment]
Related comment from https://github.com/jenkinsci/ec2-fleet-plugin/issues/144#issuecomment-559810078

> input for the block device ID -- our build agents have a 150GB storage device attached
> Constraints on cost
> Tags for the instances
> Security groups
> Would we be assured that the spot requests would be automatically cancelled when removed from the configuration? How would we be assured that unrelated spot requests would not be deleted accidentally?

1. Good point, added as feature request #161
1. Well, even without fleet creation it could be case when fleet will be scaled to very big number, that's why fleet and label configuration allow to specify max fleet size. Additionally to that, use https://aws.amazon.com/aws-cost-management/aws-budgets
1. What is use case for ```Tags for instances```, currently plugin tags all EC2 instances with fleet name ```ec2-fleet-plugin:cloud-name=<MyCloud>```?
1. Security groups added as feature request #162 do you need VPC support in that case?
1. I think this point has two parts:
   - Plugin will take care about unused fleets
   - Label based configuration uses Cloud Formation to provision EC2 Spot Request, it's never delete fleet directly, and consume Stacks based on attached tags related only to plugin.

**Comment by ianfixes** [comment]
Sorry, I should have been more specific about constraints on cost.  I was talking about `"SpotPrice"` per instance, not the overall cost.  I would plan to control the total cost by setting the upper limit on how many build agents would run, and just make sure that my individual rate for machine time is reasonable.

I'm not sure how much of a concern this is in practice.  I am operating at a small scale.

**Comment by terma** [comment]
@ianfixes I see, interesting. Do you want to set one price for EC2 Spot Request, or you want to set per group of instances in Spot Request or probably to have dynamic price based on some other conditions. It will be really good if you could mention your use case. Thx.

**Comment by ianfixes** [comment]
Below I've posted the JSON I currently use to request my build agent spot fleets, using `aws ec2 request-spot-fleet --spot-fleet-request-config file://this_file.json`.  

Note that a lot of this definition is repetitive.  We have an upper limit on what we want to spend on instances, and lower limit on how much performance we want.  For our needs in particular, this worked out to the following:

```
            "InstanceType": "m4.xlarge",
            "SpotPrice": "0.2"

            "InstanceType": "r3.xlarge",
            "SpotPrice": "0.333"

            "InstanceType": "m3.xlarge",
            "SpotPrice": "0.266"

            "InstanceType": "r4.xlarge",
            "SpotPrice": "0.266"
```

The full definition includes the fleet role, network interfaces, security groups, whether we want public or private IP addresses, our desired tags for the instances, the AMI, and the block device.

```json
{
    "AllocationStrategy": "lowestPrice",
    "OnDemandAllocationStrategy": "lowestPrice",
    "ExcessCapacityTerminationPolicy": "default",
    "OnDemandFulfilledCapacity": 0.0,
    "IamFleetRole": "arn:aws:iam::123412341234:role/aws-ec2-spot-fleet-tagging-role",
    "LaunchSpecifications": [
        {
            "NetworkInterfaces": [
                {
                    "SubnetId": "subnet-dbdcdede",
                    "Groups": [ "sg-dc001122" ],
                    "DeviceIndex": 0,
                    "DeleteOnTermination": true,
                    "AssociatePublicIpAddress": true,
                    "SecondaryPrivateIpAddressCount": 0
                }
            ],
            "TagSpecifications": [
                {
                    "ResourceType": "instance",
                    "Tags": [
                        {
                            "Value": "production",
                            "Key": "billing_environment"
                        }
                    ]
                }
            ],
            "ImageId": "ami-abcdef0123456789",
            "BlockDeviceMappings": [
                {
                    "DeviceName": "/dev/sda1",
                    "Ebs": {
                        "SnapshotId": "snap-0a0987654321",
                        "DeleteOnTermination": true,
                        "VolumeType": "gp2",
                        "VolumeSize": 150
                    }
                }
            ],
            "KeyName": "jenkins-build-agent-key",
            "InstanceType": "m4.xlarge",
            "SpotPrice": "0.2"
        },
        {
            "NetworkInterfaces": [
                {
                    "SubnetId": "subnet-dbdcdede",
                    "Groups": [ "sg-dc001122" ],
                    "DeviceIndex": 0,
                    "DeleteOnTermination": true,
                    "AssociatePublicIpAddress": true,
                    "SecondaryPrivateIpAddressCount": 0
                }
            ],
            "TagSpecifications": [
                {
                    "ResourceType": "instance",
                    "Tags": [
                        {
                            "Value": "production",
                            "Key": "billing_environment"
                        }
                    ]
                }
            ],
            "ImageId": "ami-abcdef0123456789",
            "BlockDeviceMappings": [
                {
                    "DeviceName": "/dev/sda1",
                    "Ebs": {
                        "SnapshotId": "snap-0a0987654321",
                        "DeleteOnTermination": true,
                        "VolumeType": "gp2",
                        "VolumeSize": 150
                    }
                }
            ],
            "KeyName": "jenkins-build-agent-key",
            "InstanceType": "r3.xlarge",
            "SpotPrice": "0.333"
        },
        {
            "NetworkInterfaces": [
                {
                    "SubnetId": "subnet-dbdcdede",
                    "Groups": [ "sg-dc001122" ],
                    "DeviceIndex": 0,
                    "DeleteOnTermination": true,
                    "AssociatePublicIpAddress": true,
                    "SecondaryPrivateIpAddressCount": 0
                }
            ],
            "TagSpecifications": [
                {
                    "ResourceType": "instance",
                    "Tags": [
                        {
                            "Value": "production",
                            "Key": "billing_environment"
                        }
                    ]
                }
            ],
            "ImageId": "ami-abcdef0123456789",
            "BlockDeviceMappings": [
                {
                    "DeviceName": "/dev/sda1",
                    "Ebs": {
                        "SnapshotId": "snap-0a0987654321",
                        "DeleteOnTermination": true,
                        "VolumeType": "gp2",
                        "VolumeSize": 150
                    }
                }
            ],
            "KeyName": "jenkins-build-agent-key",
            "InstanceType": "m3.xlarge",
            "SpotPrice": "0.266"
        },
        {
            "NetworkInterfaces": [
                {
                    "SubnetId": "subnet-dbdcdede",
                    "Groups": [ "sg-dc001122" ],
                    "DeviceIndex": 0,
                    "DeleteOnTermination": true,
                    "AssociatePublicIpAddress": true,
                    "SecondaryPrivateIpAddressCount": 0
                }
            ],
            "TagSpecifications": [
                {
                    "ResourceType": "instance",
                    "Tags": [
                        {
                            "Value": "production",
                            "Key": "billing_environment"
                        }
                    ]
                }
            ],
            "ImageId": "ami-abcdef0123456789",
            "BlockDeviceMappings": [
                {
                    "DeviceName": "/dev/sda1",
                    "Ebs": {
                        "SnapshotId": "snap-0a0987654321",
                        "DeleteOnTermination": true,
                        "VolumeType": "gp2",
                        "VolumeSize": 150
                    }
                }
            ],
            "KeyName": "jenkins-build-agent-key",
            "InstanceType": "r4.xlarge",
            "SpotPrice": "0.266"
        }
    ],
    "SpotPrice": "0.333",
    "TargetCapacity": 1,
    "OnDemandTargetCapacity": 0,
    "TerminateInstancesWithExpiration": true,
    "Type": "maintain",
    "ValidFrom": "2019-01-31T13:17:25.000Z",
    "ValidUntil": "2020-01-31T13:17:25.000Z",
    "ReplaceUnhealthyInstances": true,
    "InstanceInterruptionBehavior": "terminate",
    "InstancePoolsToUseCount": 7
}
```

**Comment by terma** [comment]
@ianfixes have you tried to use [SpotMaxTotalPrice](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_SpotFleetRequestConfigData.html) to limit budget for fleet?

**Comment by ianfixes** [comment]
No, my reading of that parameter was that it's an alternative way to control the number of instances in the request (i.e. "spin up instances until this max price is reached" instead of "spin up 4 instances at the price points I've listed").

**Pull request merged**
