### PR TITLE
Remove terminated or missing spot instances

### PR DESCRIPTION
**Pull request by jimcooley**
Refactored `updateStatus()` to remove Jenkins nodes from the spot fleet that are missing, terminated, stopped, stopping, or shutting-down.

This PR addresses #11 and #9 as well as the root cause of #37 and possibly #36.

### CODE REVIEW

**Comment by stibi** [comment]
Thank a lot! I'll give it a try and test it on our Jenkins environment.

**Comment by jzila** [comment]
🎊

**Comment by bgaillard** [comment]
Hi, we also installed a plugin based on this PR and did not observe unexpected terminated / missing nodes in Jenkins as before.

For us merging this PR is very important, otherwise the plugin is simply not usable.

**Comment by bgaillard** [comment]
@schmutze Thanks a lot for this merge and for your reactivity on this !

**Comment by bertjwregeer** [comment]
I've placed the following in a Job DSL Jenkins build that runs every 5 minutes:

```
for (aSlave in hudson.model.Hudson.instance.slaves) {
  println('====================');
  println('Name: ' + aSlave.name);
  println('\tcomputer.isOffline: ' + aSlave.getComputer().isOffline());
  println('\tcomputer.countBusy: ' + aSlave.getComputer().countBusy());
  if (aSlave.getComputer().isOffline()) {
    println('\tShutting down node!!!!');
    aSlave.getComputer().doDoDelete();
  }
}
```

Which will clean up all offline slaves. As it happens, there are also slaves that are marked offline, but are still valid ec2-fleet instances, however the SSH launcher isn't connecting to them, once they are removed the ec2-fleet plugin will re-add them and the SSH launcher will connect and jobs will start running on them.

**Comment by snowblink** [comment]
How do we get a new release of the plugin which includes this change?

**Comment by bgaillard** [comment]
Hi @snowblink,

> How do we get a new release of the plugin which includes this change?

For now because the changes are not integrated in a new release you have to compile the plugin by yourself and install it manually in Jenkins with the following commands.

```
git clone git@github.com:jimcooley/ec2-fleet-plugin.git
cd ec2-fleet-plugin
mvn install
```

This generates a `target/ec2-fleet.hpi` file you can install manually in Jenkins.

Hope this helps.

**Comment by schmutze** [comment]
I will push a new release after re:Invent next week. We have some workshops using the plugin and I don't want to make any changes until the workshops are complete.

**Comment by bgaillard** [comment]
Hi @schmutze, coming back to know if you had time to prepare a new release of the plugin ?

**Comment by mr337** [comment]
We are hurting from this too. Don't mind a compiling myself but a release would be super handy to stay in sync.

**Comment by schmutze** [comment]
Ack - I'll get on it.

**Comment by schmutze** [comment]
Thank you @jimcooley and all.
Released in [1.1.9](https://updates.jenkins.io/download/plugins/ec2-fleet/1.1.9/ec2-fleet.hpi).

**Pull request merged**
